version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '8000:8000'
    networks:
      - app-network

  wallet-service:
    build:
      context: ./wallet-service
    ports:
      - '7000:7000'
    networks:
      - app-network

  mongo-user:
    image: mongo:4.4
    container_name: mongo-user
    ports:
      - '27017:27017'
    volumes:
      - mongo-user-data:/data/db
    networks:
      - app-network

  mongo-wallet:
    image: mongo:4.4
    container_name: mongo-wallet
    ports:
      - '27018:27017'
    volumes:
      - mongo-wallet-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - user-service
      - wallet-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-user-data:
  mongo-wallet-data:
